import Sidebar from "@/components/Sidebar";
import RightBar from "src/components/Rightbar";
import "./global.css";
export const metadata = {
  title: "GoMeal",
  description: "Generated by Kutlu",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="container">
        <Sidebar />
        <div className="main">{children}</div>
        <RightBar />
      </body>
    </html>
  );
}
