import Sidebar  from '@/components/Sidebar'
import './global.css'
export const metadata = {
  title: 'GoMeal',
  description: 'Generated by Kutlu',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='container'>
      <Sidebar/>
      {children}
      </body>
    </html>
  )
}
